# typed: false
# frozen_string_literal: true

# This file was generated by scripts/generate_formula.sh
# DO NOT EDIT THIS FILE MANUALLY

class MayafluxDev < Formula
  desc "Development version of MayaFlux - high-performance audio-visual computation library"
  homepage "https://github.com/MayaFlux/MayaFlux"
  version "0.1.0-dev"
  
  on_arm do
    url "https://github.com/MayaFlux/MayaFlux/releases/download/v0.1.0-dev/MayaFlux-0.1.0-dev-macos-arm64.tar.gz"
    sha256 "85c1560eb1b4a3a852c237fc127a688b43a6a77e88aee1ee170ae63ba9037d56"
  end
  
  on_intel do
    url "https://github.com/MayaFlux/MayaFlux/releases/download/v0.1.0-dev/MayaFlux-0.1.0-dev-macos-x64.tar.gz"
    sha256 "3ef38da9edc3b45210bc3488de065671663a8062de7f77b013704c7629808031"
  end
  
  depends_on "pkg-config"
  depends_on "llvm"
  depends_on "ffmpeg"
  depends_on "rtaudio"
  depends_on "glfw"
  depends_on "glm"
  depends_on "eigen"
  depends_on "fmt"
  depends_on "magic_enum"
  depends_on "onedpl"
  depends_on "googletest"
  depends_on "vulkan-headers"
  depends_on "vulkan-loader"
  depends_on "vulkan-tools"
  depends_on "vulkan-validationlayers"
  depends_on "vulkan-utility-libraries"
  depends_on "spirv-tools"
  depends_on "spirv-cross"
  depends_on "shaderc"
  depends_on "glslang"
  depends_on "molten-vk"
  
  def install
    ohai "Installing STB headers..."
    stb_install_dir = prefix/"include"/"stb"
    stb_install_dir.mkpath
    
    stb_headers = [
      "stb_image.h",
      "stb_image_write.h",
      "stb_image_resize2.h",
      "stb_truetype.h",
      "stb_rect_pack.h"
    ]
    
    stb_headers.each do |header|
      system "curl", "-fL", 
             "https://raw.githubusercontent.com/nothings/stb/master/#{header}",
             "-o", stb_install_dir/header
    end
    
    bin.install Dir["bin/*"]
    lib.install Dir["lib/*"]
    share.install Dir["share/*"]
    (prefix/"include").install Dir["include/*"]
    
    (prefix/"env.sh").write <<~SHELL
      # MayaFlux Environment Setup
      export MAYAFLUX_ROOT="#{opt_prefix}"
      export PATH="\$MAYAFLUX_ROOT/bin:\$PATH"
      export CMAKE_PREFIX_PATH="\$MAYAFLUX_ROOT:\$CMAKE_PREFIX_PATH"
      export STB_ROOT="\$MAYAFLUX_ROOT/include/stb"
      export CPATH="\$STB_ROOT:\$CPATH"
      
      LLVM_PREFIX="#{Formula["llvm"].opt_prefix}"
      export PATH="\$LLVM_PREFIX/bin:\$PATH"
      export LLVM_DIR="\$LLVM_PREFIX/lib/cmake/llvm"
      export Clang_DIR="\$LLVM_PREFIX/lib/cmake/clang"
      export CMAKE_PREFIX_PATH="\$LLVM_PREFIX/lib/cmake:\$CMAKE_PREFIX_PATH"
      
      if [ -f "#{Formula["molten-vk"].opt_prefix}/share/vulkan/icd.d/MoltenVK_icd.json" ]; then
        export VK_ICD_FILENAMES="#{Formula["molten-vk"].opt_prefix}/share/vulkan/icd.d/MoltenVK_icd.json"
      elif [ -f "#{Formula["molten-vk"].opt_prefix}/etc/vulkan/icd.d/MoltenVK_icd.json" ]; then
        export VK_ICD_FILENAMES="#{Formula["molten-vk"].opt_prefix}/etc/vulkan/icd.d/MoltenVK_icd.json"
      fi
    SHELL
    
    (prefix/".version").write(version.to_s)
  end
  
  def caveats
    <<~EOS
      MayaFlux #{version} has been installed!
      
      To set up your environment, add this to your ~/.zshenv:
        export MAYAFLUX_ROOT="#{opt_prefix}"
        source "\$MAYAFLUX_ROOT/env.sh"
      
      Or run manually:
        source #{opt_prefix}/env.sh
    EOS
  end
  
  test do
    assert_predicate prefix/".version", :exist?
    assert_match version.to_s, (prefix/".version").read if (prefix/".version").exist?
    
    assert_predicate prefix/"include"/"stb"/"stb_image.h", :exist?
  end
end
