#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

REPO="MayaFlux/MayaFlux"

API_URL="https://api.github.com/repos/$REPO/releases"
AUTH_HEADER=""
if [[ -n "${GITHUB_TOKEN:-}" ]]; then
    AUTH_HEADER="-H 'Authorization: token $GITHUB_TOKEN'"
fi

echo "Fetching latest release from GitHub..."
if [[ -n "$AUTH_HEADER" ]]; then
    RELEASE_JSON=$(eval curl -s -H "Accept: application/vnd.github.v3+json" "$AUTH_HEADER" "\"$API_URL\"")
else
    RELEASE_JSON=$(curl -s -H "Accept: application/vnd.github.v3+json" "$API_URL")
fi

if [[ -z "$RELEASE_JSON" ]] || [[ "$RELEASE_JSON" == "[]" ]]; then
    echo "ERROR: Could not fetch releases"
    exit 1
fi

TAG=$(echo "$RELEASE_JSON" | grep -m1 '"tag_name"' | sed 's/.*"tag_name":\s*//' | sed 's/[",]//g' | xargs)
if [ -z "$TAG" ]; then
    echo "ERROR: Could not extract tag from release data"
    exit 1
fi

echo "Latest tag: $TAG"

ASSET_URL=$(python3 -c "
import json, sys
data = json.loads(sys.stdin.read())
if isinstance(data, list):
    data = data[0]
for asset in data.get('assets', []):
    url = asset.get('browser_download_url', '')
    if 'macos-arm64' in url and url.endswith('.tar.gz'):
        print(url)
        break
" <<<"$RELEASE_JSON")

if [ -z "$ASSET_URL" ]; then
    echo "WARNING: No direct asset URL found, constructing..."
    CLEAN_TAG=${TAG#v}

    PATTERNS=(
        "MayaFlux-${CLEAN_TAG}-macos-arm64.tar.gz"
        "MayaFlux-${TAG}-macos-arm64.tar.gz"
    )

    for PATTERN in "${PATTERNS[@]}"; do
        TEST_URL="https://github.com/$REPO/releases/download/${TAG}/${PATTERN}"
        echo "Trying: $TEST_URL"
        if curl -s -I "$TEST_URL" 2>/dev/null | head -1 | grep -q "200"; then
            ASSET_URL="$TEST_URL"
            break
        fi
    done
fi

if [ -z "$ASSET_URL" ]; then
    echo "ERROR: Could not find download URL"
    exit 1
fi

echo "Download URL: $ASSET_URL"

TEMP_FILE=$(mktemp)
echo "Downloading to calculate SHA256..."
curl -fL --progress-bar "$ASSET_URL" -o "$TEMP_FILE"

if [[ ! -s "$TEMP_FILE" ]]; then
    echo "ERROR: Download failed or empty file"
    rm -f "$TEMP_FILE"
    exit 1
fi

SHA256=$(shasum -a 256 "$TEMP_FILE" | awk '{print $1}')
rm -f "$TEMP_FILE"

echo "SHA256: $SHA256"
VERSION=${TAG#v}

mkdir -p Formula

cat >Formula/mayaflux-dev.rb <<RUBY
# typed: false
# frozen_string_literal: true

# This file was generated by scripts/generate_formula.sh
# DO NOT EDIT THIS FILE MANUALLY

class MayafluxDev < Formula
  desc "Development version of MayaFlux - high-performance audio-visual computation library"
  homepage "https://github.com/MayaFlux/MayaFlux"
  version "$VERSION"
  url "$ASSET_URL"
  sha256 "$SHA256"
  
  depends_on "pkg-config"
  depends_on "llvm"
  depends_on "ffmpeg"
  depends_on "rtaudio"
  depends_on "glfw"
  depends_on "glm"
  depends_on "eigen"
  depends_on "fmt"
  depends_on "magic_enum"
  depends_on "onedpl"
  depends_on "googletest"
  depends_on "vulkan-headers"
  depends_on "vulkan-loader"
  depends_on "vulkan-tools"
  depends_on "vulkan-validationlayers"
  depends_on "vulkan-utility-libraries"
  depends_on "spirv-tools"
  depends_on "spirv-cross"
  depends_on "shaderc"
  depends_on "glslang"
  depends_on "molten-vk"
  
  def install
    ohai "Installing STB headers..."
    stb_install_dir = prefix/"include"/"stb"
    stb_install_dir.mkpath
    
    stb_headers = [
      "stb_image.h",
      "stb_image_write.h",
      "stb_image_resize2.h",
      "stb_truetype.h",
      "stb_rect_pack.h"
    ]
    
    stb_headers.each do |header|
      system "curl", "-fL", 
             "https://raw.githubusercontent.com/nothings/stb/master/#{header}",
             "-o", stb_install_dir/header
    end
    
    bin.install Dir["bin/*"]
    lib.install Dir["lib/*"]
    share.install Dir["share/*"]
    (prefix/"include").install Dir["include/*"]
    
    (prefix/"env.sh").write <<~SHELL
      # MayaFlux Environment Setup
      export MAYAFLUX_ROOT="#{opt_prefix}"
      export PATH="\\\$MAYAFLUX_ROOT/bin:\\\$PATH"
      export CMAKE_PREFIX_PATH="\\\$MAYAFLUX_ROOT:\\\$CMAKE_PREFIX_PATH"
      export STB_ROOT="\\\$MAYAFLUX_ROOT/include/stb"
      export CPATH="\\\$STB_ROOT:\\\$CPATH"
      
      LLVM_PREFIX="#{Formula["llvm"].opt_prefix}"
      export PATH="\\\$LLVM_PREFIX/bin:\\\$PATH"
      export LLVM_DIR="\\\$LLVM_PREFIX/lib/cmake/llvm"
      export Clang_DIR="\\\$LLVM_PREFIX/lib/cmake/clang"
      export CMAKE_PREFIX_PATH="\\\$LLVM_PREFIX/lib/cmake:\\\$CMAKE_PREFIX_PATH"
      
      if [ -f "#{Formula["molten-vk"].opt_prefix}/etc/vulkan/icd.d/MoltenVK_icd.json" ]; then
        export VK_ICD_FILENAMES="#{Formula["molten-vk"].opt_prefix}/etc/vulkan/icd.d/MoltenVK_icd.json"
      fi
    SHELL
    
    (prefix/".version").write(version.to_s)
  end
  
  def caveats
    <<~EOS
      MayaFlux #{version} has been installed!
      
      To set up your environment, add this to your ~/.zshenv:
        export MAYAFLUX_ROOT="#{opt_prefix}"
        source "\\\$MAYAFLUX_ROOT/env.sh"
      
      Or run manually:
        source #{opt_prefix}/env.sh
    EOS
  end
  
  test do
    assert_predicate prefix/".version", :exist?
    assert_match version.to_s, (prefix/".version").read if (prefix/".version").exist?
    
    assert_predicate prefix/"include"/"stb"/"stb_image.h", :exist?
  end
end
RUBY

echo "✅ Formula generated for MayaFlux version $VERSION"
echo "📦 SHA256: $SHA256"
